
services:
  backend:
    container_name: backend
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis


  web:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"